### PR TITLE
Intro on Carpentries and CodeRefinery teaching styles

### PR DESCRIPTION
**Pull request by annefou**

### CODE REVIEW

**Comment by wikfeldt** [comment]
are you planning to add some exercises Anne? There are some suggestions in issues #11 , #14, #13 which I self-assigned, but don't want to be stepping on your toes

**Comment by annefou** [comment]
@wikfeldt I did add some exercises. It is far too long now but it would be nice to get some feedback. I guess #13 would be a very good exercise for https://annefou.github.io/instructor_training/06-teaching/

**Comment by wikfeldt** [comment]
yeah i'm adding it under https://annefou.github.io/instructor_training/06-teaching/ instead!

**Comment by wikfeldt** [comment]
looks good, i'll merge now and maybe follow up with small changes

**Pull request merged**
