### PR TITLE
adding my teaching approach/thoughts

### PR DESCRIPTION
**Pull request by wikfeldt**
depends on #28

### CODE REVIEW

**Comment by wikfeldt** [comment]
actually, what's the best way to handle dependent PRs? Now I have all the same commits here as in #28

**Comment by bast** [comment]
So the PRs are identical? Or with a lot of overlap? If identical, I would close one and explain why we close. If a lot of overlap, I would merge the smaller one, then rebase the other branch after the smaller PR is merged.

**Comment by wikfeldt** [comment]
so this short PR is one commit ahead of #28 (which is much bigger)
I'll just merge the other one, rebase locally and create a new PR

**Comment by wikfeldt** [comment]
this PR is just adding my training philosophy, so merging it

**Pull request merged**
